package connect;
// Generated 21 Jan, 2016 12:48:49 AM by Hibernate Tools 4.3.1



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String class_;

    public Groups() {
    }

    public Groups(String name, String class_) {
       this.name = name;
       this.class_ = class_;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }




}


